[lio-py]: Add -ENODEV exception handler for alua_tg_pt_gp
This patch adds a exception handler for the case where:

/sys/kernel/config/target/iscsi/$IQN/tpgt_$TPGT/lun/lun_$LUN_ID/alua_tg_pt_gp

is returning -ENODEV because no symlink exists for the iSCSI Target Port in said directory.

This fixes the following python traceback:

Traceback (most recent call last):
  File "./lio_dump.py", line 257, in ?
    main()
  File "./lio_dump.py", line 248, in main
    (options, args) = parser.parse_args()
  File "/usr/lib64/python2.4/optparse.py", line 1275, in parse_args
    stop = self._process_args(largs, rargs, values)
  File "/usr/lib64/python2.4/optparse.py", line 1315, in _process_args
    self._process_long_opt(rargs, values)
  File "/usr/lib64/python2.4/optparse.py", line 1390, in _process_long_opt
    option.process(opt, value, values, self)
  File "/usr/lib64/python2.4/optparse.py", line 707, in process
    return self.take_action(
  File "/usr/lib64/python2.4/optparse.py", line 726, in take_action
    self.callback(self, opt, value, parser, *args, **kwargs)
  File "./lio_dump.py", line 88, in lio_target_configfs_dump
    value = os.read(p, 512)
OSError: [Errno 19] No such device

Signed-off-by: Nicholas A. Bellinger <nab@linux-iscsi.org>